name: Checks
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**.ts'
      - 'src/**.js'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**.ts'
      - 'src/**.js'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        id: install-deps
        run: npm ci
      - name: Cache files
        uses: actions/cache@v4
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        id: get-files
        uses: actions/cache@v4
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
      - name: Run lint
        id: run-lint
        run: npm run lint
  formatting:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        id: get-files
        uses: actions/cache@v4
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
      - name: Check formatting
        id: check-fmt
        run: 'npx prettier --check "**/*.{t,j}s"'
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get files
        id: get-files
        uses: actions/cache@v4
        with:
          path: |
            ./*
            .npm
          key: ${{ github.sha }}
      - name: Run tests
        id: run-tests
        run: npm test

